rapidsai/kvikio

- python/benchmarks/single-node-io.py
- scripts/format-all.py
Implements format checking. Use `scripts/format-all.py --check` to check the formatting of the whole project using: `isort, black, flake8, mypy, and clang-format`.
> format-all: added the --check argument

- cpp/examples/basic_io.cpp
- cpp/include/kvikio/driver.hpp
- cpp/include/kvikio/nvml.hpp
- cpp/include/kvikio/parallel_operation.hpp
- cpp/include/kvikio/utils.hpp
- python/setup.py
Set the environment variable `STATIC_CUFILE=true` to build the Python extension with static linking of cufile.
Closes https://github.com/rapidsai/kvikio/issues/4
> Support of static linking cufile when building the Python extension

- cpp/CMakeLists.txt
- cpp/examples/CMakeLists.txt
- cpp/include/kvikio/parallel_operation.hpp
- cpp/include/kvikio/utils.hpp
- python/setup.py
- python/tests/test_basic_io.py
Threads now use `cuPointerGetAttribute(CU_POINTER_ATTRIBUTE_CONTEXT)` to retrieve the appropriate CUDA context. This mean that we do not depend on the CUDA Runtime API any more :)
> Remove dependency of the CUDA Runtime API

- README.md
- cpp/include/kvikio/utils.hpp
- python/examples/hello_world.py
- python/kvikio/_lib/kvikio_cxx_api.pxd
- python/kvikio/_lib/libkvikio.pyx
- python/kvikio/cufile.py
Implement https://github.com/rapidsai/kvikio/issues/8
> IOFuture.done()

- cpp/include/kvikio/config.hpp
- cpp/include/kvikio/file_handle.hpp
- cpp/include/kvikio/posix_io.hpp
- cpp/include/kvikio/thread_pool/default.hpp
- python/kvikio/_lib/kvikio_cxx_api.pxd
- python/kvikio/_lib/libkvikio.pyx
- python/kvikio/config.py
- python/tests/test_basic_io.py
This PR introduce a compatibility mode that goes beyond the [Compatibility Mode](https://docs.nvidia.com/gpudirect-storage/api-reference-guide/topics/cufile-compatibility.html#cufile-compatibility-mode) already in cuFile. Enable this mode by setting the environment variable `KVIKIO_COMPAT_MODE=true`.
For now, this mode is very inefficient.
> POSIX read/write 

- ci/cpu/upload.sh
As pointed out by @ajschmidt8, the gpuCI running on commits is [failing](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/kvikio/job/branches/job/kvikio-cpu-cuda-build/5/CUDA=11.5/console) because we are still attempting to upload libkvikio packages even though they are not yet getting produced - once this is merged, we should be able to successfully run the upload script.
cc @madsbk
> Skip uploading libkvikio packages for now

- ci/cpu/build.sh
- ci/cpu/upload.sh
We aren't able to use `CONDA_CHANNEL` for kvikIO builds yet, so removed that variable from the builds scripts.
> Don't use `CONDA_CHANNEL` for package builds

- ci/cpu/upload.sh
Think there was a syntax error in the `conda build ... --output` command being used to locate the packages to upload - now lifting the command used by cuDF so this should work.
Also added the `--python` option to it so we can locate the different build variants of kvikIO.
> Fix conda build output command in upload script

- ci/cpu/upload.sh
Accidentally used `CONDA_BUILD_DIR` instead of `CONDA_BLD_DIR` for the upload script
> Use correct conda build dir for uploads

- python/tests/conftest.py
- python/tests/test_benchmarks.py
For testing, use a dedicated process to run commands to avoid corrupting CUDA
> test: use a dedicated process to run commands

- ci/gpu/build.sh
- cpp/include/kvikio/config.hpp
- cpp/include/kvikio/utils.hpp
Automatically enable KvikIO compatibility mode when `/run/udev` isn't readable. This typically happens when running inside a docker image not launched with `--volume /run/udev:/run/udev:ro`.
Closes  #33
> Auto detect running inside docker

- .gitignore
- conda/recipes/kvikio/meta.yaml
- python/CMakeLists.txt
- python/cmake/CMakeLists.txt
- python/cmake/kvikio_python_helpers.cmake
- python/kvikio/_lib/CMakeLists.txt
- python/pyproject.toml
- python/setup.py
This PR rewrites the Python build system to use scikit-build, enabling easier interfacing with CMake and therefore integration with C++ builds. This change should help facilitate more complicated Python/C++ build interactions like what we might need for #24.
> Replace setuptools with scikit-build in the Python build

- conda/recipes/kvikio/build.sh
- conda/recipes/kvikio/meta.yaml
- python/pyproject.toml
* Require `pip` in `host` (as it is used in the build)
* Inline the build in `meta.yaml`'s `script` (dropping `build.sh`)
* Increase `pip` verbosity (to aid in detecting build issues)
* ~~Specify `build-backend` (per [this example]( https://scikit-build.readthedocs.io/en/latest/usage.html#example-of-setup-py-cmakelists-txt-and-pyproject-toml ))~~ (this causes [a build error with `pip` on CI]( https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/kvikio/job/prb/job/kvikio-cpu-cuda-build/CUDA=11.5/87/console ) so skipped for now)
> Updates to Python build

- cpp/include/kvikio/utils.hpp
Forgot to inline `load_library()`. Fixed.
> Fix inline of `load_library()`

- ci/docs/build.sh
- cpp/CMakeLists.txt
- cpp/include/kvikio/buffer.hpp
- cpp/include/kvikio/driver.hpp
- cpp/include/kvikio/error.hpp
- cpp/include/kvikio/file_handle.hpp
- cpp/include/kvikio/shim/cufile.hpp
- cpp/include/kvikio/shim/cufile_h_wrapper.hpp
- cpp/include/kvikio/utils.hpp
Use `__has_include(<cufile.h>)` to fallback to compat mode.
The motivation here is to make KvikIO work in all circumstances so that libraries doesn't have to implement there own fallback solutions.
> Fallback to Compat mode when `cufile.h` isn't found

- cpp/include/kvikio/defaults.hpp
- cpp/include/kvikio/file_handle.hpp
- cpp/include/kvikio/parallel_operation.hpp
- cpp/include/kvikio/shim/cufile.hpp
- cpp/include/kvikio/utils.hpp
- python/benchmarks/single-node-io.py
- python/kvikio/_lib/kvikio_cxx_api.pxd
- python/kvikio/_lib/libkvikio.pyx
- python/kvikio/cufile.py
- python/kvikio/defaults.py
- python/tests/test_basic_io.py
- python/tests/test_defaults.py
Partitions parallel IO operations into tasks of size `KVIKIO_TASK_SIZE` for execution in the default thread pool.
> Implement task size for parallel IO operations

- cpp/CMakeLists.txt
lowercase "namespace" should be "NAMESPACE"
This is critical and should be merged into `branch-22.04` before release
> rapids_export(): typo in argument

- cpp/CMakeLists.txt
Forward-merge triggered by push to `branch-22.04` that creates a PR to keep `branch-22.06` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-22.04 to branch-22.06 [skip gpuci]

- python/CMakeLists.txt
This PR embeds signatures in Cython functions and classes so that they'll be accessible for normal Python help. While docstrings are currently present as expected, we still have to provide Cython with the appropriate directives to tell it that we want signatures.
> Embed Cython docstrings in generated files.

- cpp/include/kvikio/defaults.hpp
- cpp/include/kvikio/file_handle.hpp
- cpp/include/kvikio/parallel_operation.hpp
- cpp/include/kvikio/posix_io.hpp
- python/tests/test_basic_io.py
KvikIO's compatibility mode is now per `FileHandle` thus changing compatibility mode, effects all new `FileHandles` that doesn't sets the `compat_mode` argument explicitly but it never effect existing `FileHandles`.
> compat_mode per `FileHandle`

- cpp/include/kvikio/defaults.hpp
- cpp/include/kvikio/driver.hpp
- cpp/include/kvikio/file_handle.hpp
These function needs to be inline so that the header can be safely included in multiple files in the same TU without ODR violations.
> Mark detail functions as inline

- ci/gpu/build.sh
- cpp/CMakeLists.txt
- cpp/include/kvikio/buffer.hpp
- cpp/include/kvikio/driver.hpp
- cpp/include/kvikio/error.hpp
- cpp/include/kvikio/file_handle.hpp
- cpp/include/kvikio/posix_io.hpp
- cpp/include/kvikio/shim/cuda.hpp
- cpp/include/kvikio/shim/cufile.hpp
- cpp/include/kvikio/shim/utils.hpp
- cpp/include/kvikio/utils.hpp
Like we do with cuFile, dlopen the CUDA driver library
@shwina
> dlopen `libcuda.so`

- conda/recipes/kvikio/conda_build_config.yaml
- conda/recipes/kvikio/meta.yaml
- conda/recipes/libkvikio/conda_build_config.yaml
- conda/recipes/libkvikio/meta.yaml
This PR enables the usage of conda compilers to build conda packages. This is required to use `mambabuild`
> Use conda compilers

- conda/recipes/kvikio/conda_build_config.yaml
- conda/recipes/kvikio/meta.yaml
- conda/recipes/libkvikio/conda_build_config.yaml
- conda/recipes/libkvikio/meta.yaml
Forward-merge triggered by push to `branch-22.06` that creates a PR to keep `branch-22.08` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-22.06 to branch-22.08 [skip gpuci]

- conda/recipes/kvikio/meta.yaml
- conda/recipes/libkvikio/meta.yaml
- Simplify recipes using `{{ target_platform }}` for `sysroot` package and `compiler()` function in `ignore_run_exports_from`
- Add missisng `ignore_run_exports_from`
> Fix conda recipes

- cpp/CMakeLists.txt
- cpp/cmake/Modules/FindcuFile.cmake
We shouldn't presume that the CUDA Toolkit is always installed at /usr/local/cuda. Instead we use use `find_package(CUDAToolkit)` to find the correct location.
In addition since `cufile::cuFile_interface` is part of our public interface we also install the `FindcuFile.cmake` file.
> FindcuFile now searches in the current CUDA Toolkit location

- cpp/include/kvikio/error.hpp
When using a stub, calling `cuGetErrorName()` and `cuGetErrorString()` results in segfault. In this PR we check `CUDA_ERROR_STUB_LIBRARY` explicitly.
> Check stub error

- cpp/include/kvikio/defaults.hpp
- python/kvikio/cufile.py
- python/kvikio/defaults.py
Just fixing a few issues that I noticed in the docstrings.
Default task size currently seems to be [4 MB rather than 16 MB](https://github.com/rapidsai/kvikio/blob/bc7a313c68c677189ff7cd78bd4e58e16a587bda/cpp/include/kvikio/defaults.hpp#L106).
> minor docstring fixes

- python/kvikio/cufile.py
I initially did not realize the importance of aligning the offsets to 4096-byte boundaries and was experiencing slower than expected performance. It is likely to be helpful to advertise the necessity of this alignment more prominently as proposed here.
> add Notes related to page-aligned read/write methods to the Python docstrings

- conda/recipes/kvikio/meta.yaml
When `python` is a dependency, it needs to be listed in `host` & `run`. This aligns the version used when installing and makes sure `python` gets installed (and the right `kvikio` package with it) at runtime.
cc @madsbk @charlesbluca
> Require `python` in `run`

- conda/recipes/kvikio/meta.yaml
Forward-merge triggered by push to `branch-22.08` that creates a PR to keep `branch-22.10` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-22.08 to branch-22.10 [skip gpuci]

- ci/gpu/build.sh
Currently, CI skips the test of `nvcomp` because it requires `cudf`.
> CI: install cuDF to test nvCOMP

- ci/gpu/build.sh
- conda/recipes/libkvikio/build.sh
- conda/recipes/libkvikio/meta.yaml
- cpp/examples/CMakeLists.txt
- cpp/include/kvikio/driver.hpp
Test that KvikIO can be build even when cuFile isn't available and fixes a `unused variable` compile warning
> CI: build without cuFile

- cpp/cmake/fetch_rapids.cmake
Removes possibility of another projects RAPIDS.cmake being used, and removes need to always download a version.
> Use rapids-cmake 22.10 best practice for RAPIDS.cmake location

- cpp/include/kvikio/shim/cuda.hpp
- cpp/include/kvikio/shim/cufile.hpp
In order to avoid ABI incompatibilities and loading of stub libraries, we now specify the major version when loading `libcuda.so.1` and `libcufile.so.1`.
> Set version when dlopen() cuda and cufile

- python/benchmarks/single-node-io.py
- python/kvikio/zarr.py
- python/tests/test_benchmarks.py
- python/tests/test_zarr.py
which include https://github.com/zarr-developers/zarr-python/pull/934
> Use Zarr v2.13.0a2

- conda/environments/kvikio_dev_cuda11.5.yml
- conda/recipes/kvikio/meta.yaml
- conda/recipes/libkvikio/meta.yaml
- cpp/CMakeLists.txt
- cpp/examples/downstream/CMakeLists.txt
- python/CMakeLists.txt
- python/pyproject.toml
With rapids-cmake now requiring CMake 3.23.1 update consumers to correctly express this requirement
> Document that minimum required CMake version is now 3.23.1

- cpp/include/kvikio/utils.hpp
Instead of raising an exception when CUDA hasn't been initialized, `is_host_memory()` now assumes that the pointer is host memory.
> `is_host_memory()`: returns `true` when `CUDA_ERROR_NOT_INITIALIZED`

- cpp/include/kvikio/shim/cufile.hpp
- cpp/include/kvikio/shim/utils.hpp
> dlopen: now trying "libcufile.so.1", "libcufile.so.0", "libcufile.so"

- conda/environments/kvikio_dev_cuda11.5.yml
- conda/recipes/kvikio/meta.yaml
- conda/recipes/libkvikio/meta.yaml
- cpp/CMakeLists.txt
- cpp/examples/downstream/CMakeLists.txt
- python/CMakeLists.txt
- python/pyproject.toml
Forward-merge triggered by push to `branch-22.12` that creates a PR to keep `branch-23.02` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-22.12 to branch-23.02 [skip gpuci]

- .github/ops-bot.yaml
Required for the GitHub Actions migration.
> Enable copy_prs.

- python/tests/test_nvcomp.py
@thomcom can we avoid hard coding the expected compression lengths?
> nvcomp tests: update hardcoded lengths

- cpp/include/kvikio/shim/cufile.hpp
cuFile is supposed to open and close the driver automatically but because of a bug in CUDA 11.8, it sometimes segfault.
Closes https://github.com/rapidsai/kvikio/issues/159
cc. @vuule
> Manually open and close the cuFile driver

- ci/cpu/build.sh
- ci/gpu/build.sh
- conda/recipes/kvikio/meta.yaml
- conda/recipes/libkvikio/meta.yaml
This PR moves the date string from the version to the build string for conda recipes in this repository.
This is necessary to ensure that the conda packages resulting from PR builds can be installed in the same environment as nightly conda packages, which is useful for testing purposes.
Additionally, this prevents a bug from occurring where the Python builds fail because the date string it computes is different than the one computed by the C++ build, therefore causing the Python build to search for a C++ build artifact that doesn't exist.
xref: https://github.com/rapidsai/rmm/pull/1195
> Move date to build string in `conda` recipe

- python/tests/test_nvcomp.py
Mismatch in compression ratios now results in a `XFAIL`. 
In https://github.com/rapidsai/kvikio/pull/156 we allowed a small compression ratio mismatch however this isn't enough when testing on ARM. 
cc. @thomcom @AjayThorve
> nvcomp xfail compression ratios

- .github/ops-bot.yaml
These changes should've been included in #164.
They update the `ops-bot.yaml` file to enable the [Recently Updated Check](https://docs.rapids.ai/resources/recently-updated/) for `kvikio`.
Additionally, this PR removes the `external_contributors` key, since it is no longer in use.
> Update `ops-bot.yaml`  config

- cpp/include/kvikio/error.hpp
- cpp/include/kvikio/file_handle.hpp
- cpp/include/kvikio/shim/cuda.hpp
- cpp/include/kvikio/utils.hpp
- python/tests/conftest.py
- python/tests/test_basic_io.py
- python/tests/test_numpy.py
Currently, we call `cuPointerGetAttribute(..., CU_POINTER_ATTRIBUTE_CONTEXT)` to set the CUDA context for each IO task. However, this doesn't work for[ stream ordered device memory allocations](https://docs.nvidia.com/cuda/cuda-c-programming-guide/#pointer-attributes) so we now get the current cuda context instead.
Closes https://github.com/rapidsai/cudf/issues/12865
> Support of stream ordered device memory allocations (async mallocs)

- cpp/include/kvikio/posix_io.hpp
The posix-write interpreted a return value of `0` as a `EOF` error, which is isn't.
> posix_io: fix error message and allow `nbytes == 0` on write

- .gitignore
- build.sh
- legate/CMakeLists.txt
- legate/cpp/CMakeLists.txt
Implement the `build.sh` that other RAPIDS projects use.  
Running `./build.sh libkvikio kvikio legate` now works and cleaning the environment also works  `./build.sh clean`.
However, after a clean, installing `legate` doesn't work.
```
$ ./build.sh clean legate
CMake Error at /home/mkristensen/apps/miniconda3/envs/legate-0227/lib/cmake/legate_core/legate_core-config.cmake:332 (add_library):
add_library cannot create ALIAS target "legate::legate_kvikio_python"
because another target with the same name already exists.
Call Stack (most recent call first):
CMakeLists.txt:36 (legate_default_python_install)
```
If I delete the installed cmake files from the conda environment, it works again:
```
$ rm -R /home/mkristensen/apps/miniconda3/envs/legate-0227/lib/cmake/legate_kvikio
$ ./build.sh …
```
> Implement `build.sh`

- conda/recipes/kvikio/meta.yaml
This PR removes the underscore after "cuda" to align with other RAPIDS packages.
> Remove underscore in build string.

- .pre-commit-config.yaml
- cpp/include/kvikio/driver.hpp
- cpp/include/kvikio/file_handle.hpp
- cpp/include/kvikio/posix_io.hpp
- cpp/include/kvikio/shim/cuda.hpp
- cpp/include/kvikio/shim/cufile.hpp
- cpp/include/kvikio/shim/utils.hpp
- cpp/include/kvikio/utils.hpp
- legate/cpp/legate_mapping.cpp
This PR updates the clang-format version used by pre-commit.
> Update clang-format to 16.0.1.

- cpp/include/kvikio/file_handle.hpp
Adding `is_compat_mode_on()` to FileHandle to make the run-time behavior more transparent for the users.
> Add API to get compatibility mode status in a FileHandle object

- cpp/include/kvikio/shim/cufile.hpp
Rather than searching for a list of possible library names for libcufile, only look for the single ABI-compatible version of libcufile that we support. This avoids both ABI incompatibilities and loading stub libraries. It morally does what #127 attempted, but with the correct versioning suffix.
Closes #200.
> Only look for libcufile.so.0

- python/benchmarks/single-node-io.py
- python/kvikio/zarr.py
- python/tests/test_zarr.py
Some quick numbers (all IO reads):
|       | Compression Ratio | Throughput
| ----------- | :-----------: |-----------: |
| POSIX                               | n/a      | 1.63 GiB/s |
| KvikIO (compat mode)  | n/a        |   8.43 GiB/s |
| Zarr (no compression)   | n/a        |8.00 GiB/s | 
| Zarr+Snappy | 1000/322        | 10.57 GiB/s|
| Zarr+Gdeflate | 1000/27        | 29.05 GiB/s|
| Zarr+LZ4 | 1000/9        | 48.95 GiB/s|
Notice, this is just a quick benchmark to show the potential of nvCOMP. 
When Zarr v2.15 is released and https://github.com/rapidsai/kvikio/pull/131 merged, we can start optimizing. 
Additionally, when https://github.com/zarr-developers/zarr-python/pull/1396 is merged, we can introduce a wrapper for `zarr.open()` that seamlessly reads/writes to/from GPU memory and …
> Zarr+nvCOMP

- conda/recipes/libkvikio/meta.yaml
This change passes through the value of `SCCACHE_S3_NO_CREDENTIALS` to our `conda` builds, enabling devs to utilize the `sccache` cache that's populated by CI when they are reproducing build issues locally as per [these](https://docs.rapids.ai/resources/reproducing-ci/) instructions.
> Enable sccache hits for local builds

- dependencies.yaml
This PR fixes the libcufile dependency specification so that it's only specified for x86_64. It also fixes the redundant cudatoolkit re-specification for aarch64.
> Fix libcufile dependency.

- cpp/examples/basic_io.cpp
- cpp/include/kvikio/batch.hpp
- cpp/include/kvikio/shim/cufile.hpp
Fixes the [CI error](https://github.com/rapidsai/kvikio/actions/runs/5251546756/jobs/9486714890?pr=224) in #224.
Additionally, we now use the mangled name of the `CUfileOpError` to determine if cuFile's batch API is available (v12.0.1+). Previously, we used the mangled name of `cuFileBatchContextState`, which corresponds to v12.0.0+.
> Disable the batch API when in compatibility mode

- legate/pyproject.toml
- python/pyproject.toml
The pyproject.toml files list imports that do not actually occur in kvikio and can be removed.
> Clean up isort configs

- README.md
- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/recipes/kvikio/meta.yaml
- conda/recipes/libkvikio/meta.yaml
- dependencies.yaml
This PR changes CUDA 11 packaging to rely on `cuda-version` pinnings to constrain the installed version of `cudatoolkit`.
See also: https://github.com/rapidsai/cudf/pull/13615
> Use cuda-version to constrain cudatoolkit.

- notebooks/nvcomp_batch_codec.ipynb
- python/kvikio/_lib/CMakeLists.txt
- python/kvikio/_lib/libnvcomp_ll.pyx
- python/kvikio/_lib/nvcomp_ll_cxx_api.pxd
- python/kvikio/nvcomp_codec.py
- python/pyproject.toml
- python/tests/test_nvcomp_codec.py
> Add support for nvCOMP batch API

- dependencies.yaml
Forward-merge triggered by push to `branch-23.08` that creates a PR to keep `branch-23.10` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-23.08 to branch-23.10

- python/examples/zarr_cupy_nvcomp.py
- python/kvikio/nvcomp_codec.py
- python/kvikio/zarr.py
- python/tests/test_examples.py
- python/tests/test_zarr.py
Introducing `open_cupy_array()`, which is a CUDA friendly version of `zarr.open_array` that reads and writes to CuPy arrays.
> Zarr+CuPy+GDS+nvCOMP made easy

- cpp/examples/basic_io.cpp
- cpp/include/kvikio/error.hpp
- cpp/include/kvikio/file_handle.hpp
- cpp/include/kvikio/shim/cuda.hpp
`read_async()` and `write_async()` now works in compat mode by falling back to the blocking implementation
> async: fall back to blocking

- ci/release/update-version.sh
Just adds the missing file parameter to a `sed_runner` command
I've tested this locally and CI does not test this file.
> Add missed filename to sed_runner call

- .github/workflows/pr.yaml
https://github.com/rapidsai/shared-action-workflows/pull/122 was merged, so the devcontainers workflow should use `branch-23.10` for the release.
> Use branch-23.10 for devcontainers workflow.

- .github/workflows/pr.yaml
Forward-merge triggered by push to `branch-23.10` that creates a PR to keep `branch-23.12` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-23.10 to branch-23.12

- python/kvikio/_lib/libnvcomp_ll.pyx
- python/kvikio/nvcomp_codec.py
- python/tests/test_nvcomp_codec.py
This PR contains a set of performance-related improvements for the batch nvCOMP codec.
The short summary of the changes:
* Replaced multiple calls to CUDA  `memcpyAsync` with a single call to a CUDA kernel.
* Removed redundant memory allocations and copies (some of them are the result of the previous change).
* Vectorized loops, removed redundant loops.
As a result, decompression throughput on ERA5 data increased from **4** GB/s to **31** GB/s for LZ4 algorithm. For highly-compressible data from [nvCOMP benchmark](https://github.com/NVIDIA/nvcomp/blob/main/doc/Benchmarks.md), the increase is even higher: from **6** GB/s to about **110** GB/s. Other algorithms, such as GDeflate, show performance improvements as well.
Compression throughput was also improved, though the main target was …
> Improve performance of nvCOMP batch codec.

- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-120_arch-x86_64.yaml
- conda/recipes/kvikio/meta.yaml
- dependencies.yaml
- legate/pyproject.toml
- python/pyproject.toml
numcodecs 0.12 appears to have some breaking changes. I've submitted a fix upstream, but for this release of RAPIDS we'll need to upper bound the version to be safe.
xref: https://github.com/zarr-developers/numcodecs/pull/475
> Add numcodecs pin

- python/examples/zarr_cupy_nvcomp.py
- python/kvikio/zarr.py
- python/tests/test_zarr.py
... also added some more examples.
> Support no compressor in `open_cupy_array()`

- .github/workflows/pr.yaml
- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-120_arch-x86_64.yaml
- conda/recipes/kvikio/conda_build_config.yaml
- cpp/cmake/fetch_rapids.cmake
- dependencies.yaml
- python/kvikio/_lib/libnvcomp.pyx
- python/kvikio/_lib/nvcomp_cxx_api.pxd
- python/kvikio/nvcomp.py
- python/tests/test_nvcomp.py
Update the nvCOMP version used for compression/decompression to 3.0.4.
See also:
https://github.com/rapidsai/cudf/pull/13815
https://github.com/rapidsai/rapids-cmake/pull/451
> Update nvcomp to 3.0.4 (includes API changes)

- cpp/CMakeLists.txt
- cpp/cmake/thirdparty/get_gtest.cmake
Update to use non deprecated signatures for `rapids_export` functions
> Update rapids-cmake functions to non-deprecated signatures

- .github/workflows/pr.yaml
- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-120_arch-x86_64.yaml
- conda/recipes/kvikio/conda_build_config.yaml
- cpp/CMakeLists.txt
- cpp/cmake/fetch_rapids.cmake
- cpp/cmake/thirdparty/get_gtest.cmake
- dependencies.yaml
- python/kvikio/_lib/libnvcomp.pyx
- python/kvikio/_lib/nvcomp_cxx_api.pxd
- python/kvikio/nvcomp.py
- python/tests/test_nvcomp.py
Forward-merge triggered by push to `branch-23.12` that creates a PR to keep `branch-24.02` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-23.12 to branch-24.02

- ci/release/update-version.sh
- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-120_arch-x86_64.yaml
- conda/recipes/kvikio/conda_build_config.yaml
- dependencies.yaml
This PR bumps nvcomp to 3.0.6. This is needed as a hotfix for https://github.com/rapidsai/cudf/issues/15096.
Depends on:
- https://github.com/conda-forge/nvcomp-feedstock/pull/14
- https://github.com/rapidsai/rapids-cmake/pull/542
> Bump to nvcomp 3.0.6.

- ci/release/update-version.sh
- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-122_arch-x86_64.yaml
- conda/recipes/kvikio/conda_build_config.yaml
- dependencies.yaml
Fix conflicts in PR: https://github.com/rapidsai/kvikio/pull/347
> Forward-merge `branch-24.02` into `branch-24.04` [skip ci]

- ci/run_ctests.sh
- ci/run_pytests.sh
- ci/test_cpp.sh
- ci/test_python.sh
This PR adds environment-agnostic `run_{ctests,pytests}.sh` scripts, and updates `test_{cpp,python}.sh` to call them.
The `test_{cpp,python}.sh` scripts assume they're running in our CI environment, and they do more than just run the tests.
This PR allows devs and downstream consumers to only run the tests, and skip the unrelated logic in `test_{cpp,python}.sh`.
> Add environment-agnostic scripts for running ctests and pytests

- cpp/include/kvikio/buffer.hpp
- cpp/include/kvikio/error.hpp
- cpp/include/kvikio/file_handle.hpp
- cpp/include/kvikio/shim/cufile.hpp
- cpp/include/kvikio/shim/cufile_h_wrapper.hpp
Moving all the `#ifdef KVIKIO_CUFILE_FOUND` to the shim layer
> Refactor: move cufile header checks to the shim layer

- conda/recipes/kvikio/conda_build_config.yaml
- conda/recipes/kvikio/meta.yaml
- conda/recipes/libkvikio/conda_build_config.yaml
- conda/recipes/libkvikio/meta.yaml
The `sysroot*` syntax is getting phased out (conda-forge/conda-forge.github.io#2102).
The recommendation is to move to `{{ stdlib("c") }}`.
Ref https://github.com/rapidsai/build-planning/issues/39
> Migrate to `{{ stdlib("c") }}`

- cpp/include/kvikio/file_handle.hpp
- cpp/include/kvikio/posix_io.hpp
- cpp/include/kvikio/shim/cuda.hpp
> POSIX IO: use async memcpy

- python/kvikio/_lib/kvikio_cxx_api.pxd
- python/kvikio/_lib/libkvikio.pyx
- python/kvikio/cufile.py
- python/tests/test_async_io.py
Hi there,
Thanks for this great repository! I want to use the cuFile async IO in my research project and noticed this kvikio repo. However, the initial support has been done in #259 and tracked in #204, but the Python interface hasn't been done yet. So I exported the write_async and read_async to the CuFile Python class and added test case. This will be very helpful for my project where I want to do the PyTorch training computation and simultaneously load tensors from the SSDs. I created this PR because hopefully, it could be helpful for your repository as well as keeping the Python interface current.
Please let me know your thoughts. Thank you.
Best Regards,
Kun
> Initial Python Interface for cufile Async IO

- build.sh
- conda/recipes/kvikio/build.sh
- conda/recipes/kvikio/meta.yaml
Use `build.sh` in `meta.yaml`, and pass `-DFIND_KVIKIO_CPP=ON` to CMake.
xref: https://github.com/rapidsai/kvikio/pull/379#issuecomment-2113597741
Fixes https://github.com/rapidsai/kvikio/issues/378
> Fix conda recipe for kvikio

- CONTRIBUTING.md
- conda/recipes/kvikio/meta.yaml
Contributes to https://github.com/rapidsai/build-planning/issues/62.
It looks like this some of the `kvikio` conda package recipe has an unnecessary dependency on `setuptools`. I suspect that's left over from before the project was cut over to `scikit-build-core`.
This proposes removing it.
How I confirmed there were no direct uses of `setuptools` in  this project:
```shell
git grep -i setuptools
```
> remove unnecessary 'setuptools' dependency

- ci/build_wheel_python.sh
Contributes to https://github.com/rapidsai/build-planning/issues/69.
Proposes a stricter pattern for passing a `libkvikio` wheel from the `wheel-build-cpp` job that produced it into the `wheel-build-python` job wanting to use it (as a build dependency of `kvikio`). This change improves the likelihood that issues with the `libkivkio` wheels will be caught in CI.
See https://github.com/rapidsai/rmm/pull/1586 and https://github.com/rapidsai/build-planning/issues/69#issuecomment-2174556118 for details on how I tested this approach.
I didn't propose this on #369 because I hadn't quite finished testing the approach yet. But I do think we should do this for all of the C++ wheels (https://github.com/rapidsai/build-planning/issues/33).
> Avoid --find-links in wheel jobs

- python/libkvikio/libkvikio/__init__.py
__all__ tells you the names of the members, not the members themselves. Quote the members.
> Properly quote items in __all__

- .devcontainer/cuda12.2-conda/devcontainer.json
- .devcontainer/cuda12.2-pip/devcontainer.json
- .github/workflows/build.yaml
- .github/workflows/pr.yaml
- .github/workflows/test.yaml
- conda/environments/all_cuda-125_arch-x86_64.yaml
- cpp/doxygen/main_page.md
- dependencies.yaml
- docs/source/install.rst
This PR updates the latest CUDA build/test version 12.2.2 to 12.5.1.
Contributes to https://github.com/rapidsai/build-planning/issues/73
> Build and test with CUDA 12.5.1

- cpp/include/kvikio/file_handle.hpp
Currently, `FileHandle` always opens the file twice - one with and one without the `O_DIRECT`  flag.
Now, when in compatibility mode, `FileHandle` only opens the file once (without the `O_DIRECT`  flag) .
> Don't open with `O_DIRECT` when in compat mode

- cpp/include/kvikio/shim/cufile_h_wrapper.hpp
Fix the cufile-wrapper when `cuda.h` isn't available
> cufile-wrapper: include the cuda-wrapper

- cpp/include/kvikio/file_handle.hpp
There was a minor typo here. This fixes that
xref: https://github.com/rapidsai/kvikio/pull/404#discussion_r1690127650
> Fix `O_DIRECT` in `defined`

- cpp/include/kvikio/cufile_config.hpp
> `config_path()`: return a reference

- conda/environments/all_cuda-118_arch-aarch64.yaml
- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-125_arch-aarch64.yaml
- conda/environments/all_cuda-125_arch-x86_64.yaml
- dependencies.yaml
- python/kvikio/pyproject.toml
- python/libkvikio/pyproject.toml
Contributes to https://github.com/rapidsai/build-planning/issues/88
Finishes the work of dropping Python 3.9 support.
This project stopped building / testing against Python 3.9 as of https://github.com/rapidsai/shared-workflows/pull/235.
This PR updates configuration and docs to reflect that.
Checked that there were no remaining uses like this:
```shell
git grep -E '3\.9'
git grep '39'
git grep 'py39'
```
And similar for variations on Python 3.8 (to catch things that were missed the last time this was done).
> Drop Python 3.9 support

- cpp/doxygen/main_page.md
- cpp/include/kvikio/bounce_buffer.hpp
- docs/source/runtime_settings.rst
- python/kvikio/kvikio/__init__.py
- python/kvikio/kvikio/_lib/buffer.pyx
- python/kvikio/kvikio/benchmarks/single_node_io.py
- python/kvikio/kvikio/buffer.py
- python/kvikio/kvikio/defaults.py
- python/kvikio/tests/test_basic_io.py
closes #451 
closes #452
Also some refactor/clean up
> Non-static bounce buffer option

- python/kvikio/kvikio/_lib/libnvcomp_ll.pyx
- python/kvikio/kvikio/_lib/nvcomp_ll_cxx_api.pxd
This PR updates the nvcomp bindings to use nvcomp's defaults rather than hardcode the default options. The defaults changed in nvcomp 4.0.1, so this is needed for https://github.com/rapidsai/kvikio/pull/449.
> Use nvcomp defaults for algo options.

- .github/workflows/build.yaml
- .github/workflows/pr.yaml
- .github/workflows/test.yaml
- conda/environments/all_cuda-118_arch-aarch64.yaml
- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-125_arch-aarch64.yaml
- conda/environments/all_cuda-125_arch-x86_64.yaml
- conda/recipes/kvikio/meta.yaml
- cpp/doxygen/main_page.md
- dependencies.yaml
- docs/source/install.rst
- python/kvikio/pyproject.toml
- python/libkvikio/pyproject.toml
Contributes to https://github.com/rapidsai/build-planning/issues/40
This PR adds support for Python 3.12.
This is part of ongoing work to add Python 3.12 support across RAPIDS.
It temporarily introduces a build/test matrix including Python 3.12, from https://github.com/rapidsai/shared-workflows/pull/213.
A follow-up PR will revert back to pointing at the `branch-24.10` branch of `shared-workflows` once all
RAPIDS repos have added Python 3.12 support.
CI here is expected to fail until all of this project's upstream dependencies support Python 3.12.
This can be merged whenever all CI jobs are passing.
> Add support for Python 3.12, relax numcodecs pin

- cpp/include/kvikio/posix_io.hpp
The NVbench application `PARQUET_READER_NVBENCH` in libcudf currently crashes with the segmentation fault. To reproduce:
```
./PARQUET_READER_NVBENCH -d 0 -b 1 --run-once -a io_type=FILEPATH -a compression_type=SNAPPY -a cardinality=0 -a run_length=1
```
The root cause is that some (1) `thread_local`  objects on the main thread in `libcudf` and (2) `static` objects in `kvikio` are destroyed after `cudaDeviceReset()` in NVbench and upon program termination. These objects should simply be leaked, since their destructors making CUDA calls upon program termination constitutes UB in CUDA.
This simple PR is the kvikIO side of the fix. The other part is done here https://github.com/rapidsai/cudf/pull/16787.
> Intentionally leak static CUDA resources to avoid crash (part 2)

- conda/recipes/kvikio/meta.yaml
`kvikio`'s conda recipe only has an `import:` test (basically, makes `conda-build` run `python -c "import kvikio"` after building).
It doesn't ask `conda-build` to run any other tests.
Therefore, its `test:` dependency on `pytest` is unnecessary. This proposes removing it.
conda docs on how the `test:` section of a recipe works: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#test-section
> remove pytest dependency in kvikio conda recipe

- build.sh
- ci/build_wheel_python.sh
- python/kvikio/CMakeLists.txt
As of https://github.com/rapidsai/kvikio/pull/439 the `FIND_KVIKIO_CPP` variable is largely superfluous. In principle we could still choose to support users who want to build the Python package without having the C++ library already available somewhere, but that use case is vanishingly small now that we have C++ wheels and it would require the developer to intentionally build without isolation and omit the C++ wheel from the environment. For advanced use cases like that it is reasonable to ask the user to handle building the C++ library separately on their own and making it available for the Python package to find. None of the normal build cases that we support (conda, pip, devcontainers, DLFW) require this any longer.
> Remove now unnecessary variable

- cpp/include/kvikio/cufile_config.hpp
- cpp/include/kvikio/defaults.hpp
- cpp/include/kvikio/file_handle.hpp
- cpp/include/kvikio/utils.hpp
> Fix release-after-main bug in `get_primary_cuda_context` 

- cpp/include/kvikio/utils.hpp
> nvtx support macos

- python/kvikio/kvikio/_lib/arr.pxd
- python/kvikio/kvikio/_lib/arr.pyi
- python/kvikio/kvikio/_lib/arr.pyx
* Add return type to `asarray` (makes easy to use with other typed values)
* Include `asarray` in `pxd` for faster access within other Cython modules
> Touch ups to `Array`

- cpp/include/kvikio/bounce_buffer.hpp
- cpp/include/kvikio/defaults.hpp
- cpp/include/kvikio/posix_io.hpp
- cpp/include/kvikio/shim/cuda.hpp
- cpp/include/kvikio/shim/cufile.hpp
- cpp/include/kvikio/shim/utils.hpp
- cpp/include/kvikio/utils.hpp
We need to export static class methods that returns a reference to a static variable like we do with inline functions: https://github.com/rapidsai/kvikio/issues/442
> Visibility of static class methods

- ci/build_docs.sh
- ci/test_cpp.sh
- ci/test_python.sh
Contributes to https://github.com/rapidsai/build-planning/issues/106
Proposes specifying the RAPIDS version in `conda install` calls that install CI artifacts, to reduce the risk of CI jobs picking up artifacts from other releases.
> make conda installs in CI stricter

- cpp/include/kvikio/defaults.hpp
- cpp/include/kvikio/file_handle.hpp
- cpp/include/kvikio/posix_io.hpp
This PR makes a couple of small, general improvements.
- Improve the use of `std::tolower` to avoid UB. References [cppreference](https://en.cppreference.com/w/cpp/string/byte/tolower).
- Improve the readability of POSIX read/write interface.
- Improve the use of `std::map` to avoid a repeated search in the self-balancing BST, which takes `O(n)`.
> Small improvements

- python/kvikio/kvikio/_lib/remote_handle.pyx
Makes a few improvements to the Cython logic of `_to_string`:
* Types the input as `str`: This allows Cython to use CPython API relevant for the specific type (it will check type on entry)
* Do `is not None` check first: This way when Cython generates additional `None` checks inside the branch, the compiler can optimize them out
* Use `str`'s `encode` method: Cython makes a direct CPython call to generate `bytes` and then extracts the pointer and size for C++ to copy
> Simplify `_to_string` encoding of Python `str`s

- python/kvikio/kvikio/_lib/arr.pyx
These are all pure C functions implemented in Cython. They do not raise. [Cython 3 adds checks for exceptions]( https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html#exception-values-and-noexcept ) in these functions, which is unnecessary given none of these set exceptions. So add `noexcept` to turn off these Cython checks.
> Mark all of `Array`'s `nogil` `cdef` functions as `noexcept`

- cpp/cmake/thirdparty/get_libcurl.cmake
Works around https://github.com/curl/curl/issues/15351 . We cache the `BUILD_TESTING` cache variable when it exists so that our tests are enabled when building curl from source.
> Disabling curl tests doesn't now disable kvikio cpp tests

- python/kvikio/kvikio/_lib/arr.pyx
In `Array`, `Py_ssize_t[::1]` objects are currently backed by [CPython `array`'s]( https://cython.readthedocs.io/en/latest/src/userguide/memoryviews.html#cpython-array-module ) with some internal bits expressed in Cython. However these are not compatible with [Python's Limited API and Stable ABI]( https://docs.python.org/3/c-api/stable.html#c-api-stability ). To address that, switch to [Cython's own `array` type]( https://cython.readthedocs.io/en/latest/src/userguide/memoryviews.html#cython-arrays ). As this is baked into Cython and doesn't use anything special, it is compatible with Python's Limited API and Stable ABI.
xref: https://github.com/rapidsai/build-planning/issues/42
> Use Cython's `array` to back `Py_ssize_t[::1]`

- conda/environments/all_cuda-118_arch-aarch64.yaml
- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-125_arch-aarch64.yaml
- conda/environments/all_cuda-125_arch-x86_64.yaml
- cpp/include/kvikio/remote_handle.hpp
- dependencies.yaml
- python/kvikio/kvikio/_lib/remote_handle.pyx
- python/kvikio/kvikio/benchmarks/s3_io.py
- python/kvikio/kvikio/remote_file.py
- python/kvikio/pyproject.toml
- python/kvikio/tests/test_benchmarks.py
- python/kvikio/tests/test_http_io.py
- python/kvikio/tests/test_s3_io.py
Implements AWS S3 read support using libcurl:
```python
import kvikio
import cupy
with kvikio.RemoteFile.from_s3_url("s://my-bucket/my-file") as f:
ary = cupy.empty(f.nbytes, dtype="uint8")
f.read(ary)
```
Supersedes https://github.com/rapidsai/kvikio/pull/426
> Remote IO: S3 support 

- ci/build_wheel_cpp.sh
Since https://github.com/rapidsai/kvikio/pull/479, the libkvikio wheel now includes platform-specific files. Stop tagging the wheel as "any".
> Stop tagging wheels as arch-agnostic

- cpp/include/kvikio/shim/cuda_h_wrapper.hpp
Don't use macros for CUDA driver functions, since that does not play nice with `decltype()`. Revert to using type-erased stubs.
> Don't use macros for cuda driver functions

- cpp/include/kvikio/shim/libcurl.hpp
When building with conda, the `__FILE__` macro will contain the (long) conda build path. At install time, this is replaced by the actual path, which may be shorter. Any extra characters are replaced by `\0`.
The extra `\0` is problematic if `CurlHandle` later throws an exception to Cython since while converting the exception to Python, Cython might truncate the error message.
> CurlHandle: fix error message handling 

- cpp/CMakeLists.txt
- cpp/include/kvikio/file_handle.hpp
- cpp/src/file_handle.cpp
- cpp/src/remote_handle.cpp
... also don't build `remote_handle.cpp` if `KvikIO_REMOTE_SUPPORT=OFF`, which fixes https://github.com/rapidsai/kvikio/issues/538
> Moving details in file_handle.hpp to .cpp

- conda/environments/all_cuda-118_arch-aarch64.yaml
- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-125_arch-aarch64.yaml
- conda/environments/all_cuda-125_arch-x86_64.yaml
- dependencies.yaml
- python/kvikio/pyproject.toml
Due to a bug in cuda-python we must disallow cuda-python 12.6.1 and 11.8.4. This PR disallows those versions.
See https://github.com/rapidsai/build-planning/issues/116 for more information.
> Disallow cuda-python 12.6.1 and 11.8.4

- cpp/CMakeLists.txt
The CUDA and cufile include directories should not be exported as absolute paths when installing, only in the build tree. Add a `$<BUILD_INTERFACE>` generator expression.
> Fix exporting of include directories

- python/libkvikio/libkvikio/load.py
Contributes to https://github.com/rapidsai/build-planning/issues/118
Modifies `libkvikio.load_library()` in the following ways:
* prefer wheel-provided `libkvikio.so` to system installation
* expose environment variable `RAPIDS_LIBKVIKIO_PREFER_SYSTEM_LIBRARY` for switching that preference
* load `libkvikio.so` with `RTLD_LOCAL`, to prevent adding symbols to the global namespace ([dlopen docs](https://linux.die.net/man/3/dlopen))
Tested the general approach on https://github.com/rapidsai/cudf/pull/17316 and https://github.com/rapidsai/cuspatial/pull/1483.
> prefer wheel-provided libkvikio.so, use RTLD_LOCAL

- .pre-commit-config.yaml
- cpp/CMakeLists.txt
- cpp/cmake/Modules/FindCUDAToolkit.cmake
Backport to get
https://gitlab.kitware.com/cmake/cmake/-/commit/b38a8e77cb3c8401b3022a68f07a4fd77b290524, so that `find_library()` finds `libcufile` correctly.
> Backport `FindCUDAToolkit` from CMake 3.31

- .github/workflows/pr.yaml
- python/libkvikio/libkvikio/load.py
Contributes to https://github.com/rapidsai/build-planning/issues/118
The pattern introduced in #551 breaks editable installs in devcontainers. In that type of build, `libkvikio.so` is built outside of the wheel but **not installed**, so it can't be found by `ld`. Extension modules in `kvikio` are able to find it via RPATHs instead.
This proposes:
* try-catching the entire library-loading attempt, to silently do nothing in cases like that
* adding an import of the `kvikio` Python library in the `devcontainers` CI job, as a smoke test to catch issues like this in the future
Reproduced that with the CUDA 12.5 pip devcontainers today:
```shell
build-all
python -c "import kvikio"
```
Confirmed that the changes in this PR fix that.
> fix library-loading issues in editable installs

- python/kvikio/tests/test_async_io.py
This PR fixes #558 
The root cause is that POSIX and cuFile report different error messages for the same invalid operation which attempts to read from a write-only file. The unit test needs to take account of these different messages.
> Fix the pytest error for async io

- conda/environments/all_cuda-118_arch-aarch64.yaml
- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-125_arch-aarch64.yaml
- conda/environments/all_cuda-125_arch-x86_64.yaml
- dependencies.yaml
- python/kvikio/pyproject.toml
Now that some upstream bugs have been fixed, we can allow cuda-python 12.6.2 and 11.8.5.
See https://github.com/NVIDIA/cuda-python/issues/226#issuecomment-2472355738 for more information.
> Remove upper bounds on cuda-python to allow 12.6.2 and 11.8.5

- cpp/CMakeLists.txt
- cpp/examples/basic_io.cpp
- cpp/include/kvikio/file_handle.hpp
- cpp/include/kvikio/remote_handle.hpp
- cpp/include/kvikio/shim/cufile.hpp
- cpp/include/kvikio/shim/cufile_h_wrapper.hpp
- python/kvikio/kvikio/_lib/cufile_driver.pyx
- python/kvikio/kvikio/benchmarks/utils.py
- python/kvikio/kvikio/cufile_driver.py
- python/kvikio/tests/test_cufile_driver.py
Fixes https://github.com/rapidsai/kvikio/issues/566
To clean up and make cufile capability detection more robust,  we now use `cuFileGetVersion()`. 
Should fix the nightly failure: https://github.com/rapidsai/kvikio/actions/runs/12133477083/job/33877440755
NB:  `cuFileGetVersion()` first became available in cufile v1.8 (CTK v12.3) thus the stream and batch API detection will return false for  versions older than v1.8. I think this is acceptable for robustness.
> cufile version 

- conda/environments/all_cuda-118_arch-aarch64.yaml
- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-125_arch-aarch64.yaml
- conda/environments/all_cuda-125_arch-x86_64.yaml
- dependencies.yaml
- python/kvikio/pyproject.toml
We require a newer cuda-python lower bound for new features and to use the new layout.
This will fix a number of errors observed when the runtime version of cuda-python is older than the version used to build packages using Cython features from cuda-python.
See https://github.com/rapidsai/build-planning/issues/117#issuecomment-2524250915 for details.
> Update cuda-python lower bounds to 12.6.2 / 11.8.5

- conda/environments/all_cuda-118_arch-aarch64.yaml
- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-125_arch-aarch64.yaml
- conda/environments/all_cuda-125_arch-x86_64.yaml
- conda/recipes/kvikio/conda_build_config.yaml
- conda/recipes/libkvikio/conda_build_config.yaml
- cpp/cmake/thirdparty/get_libcurl.cmake
- dependencies.yaml
This PR uses `libcurl` 8.5.0 at build time, and should permit `>=8.5.0,<9.0a0` at runtime. This is needed to align with conda-forge which uses `libcurl` 8, and also gets a new enough minor version to avoid some known CVEs.
> Use curl >=8.5.0 to align with conda-forge and avoid CVEs.

- cpp/CMakeLists.txt
This PR fixes a CMake bug introduced in https://github.com/rapidsai/kvikio/pull/581 where `libcurl` is unconditionally compiled.
> Fix the misplaced libcurl in CMake

- conda/environments/all_cuda-118_arch-aarch64.yaml
- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-125_arch-aarch64.yaml
- conda/environments/all_cuda-125_arch-x86_64.yaml
- conda/recipes/kvikio/conda_build_config.yaml
- conda/recipes/kvikio/meta.yaml
- conda/recipes/libkvikio/conda_build_config.yaml
- conda/recipes/libkvikio/meta.yaml
- dependencies.yaml
conda-forge is using GCC 13 for CUDA 12 builds. This PR updates CUDA 12 conda builds to use GCC 13, for alignment.
These PRs should be merged in a specific order, see https://github.com/rapidsai/build-planning/issues/129 for details.
> Use GCC 13 in CUDA 12 conda builds.

- .pre-commit-config.yaml
- dependencies.yaml
- python/kvikio/pyproject.toml
- python/libkvikio/pyproject.toml
Follow-up to #478
Adds a matrix filter `use_cuda_wheels` in the `dependencies.yaml` list used for `libkvikio`'s `nvcomp` dependency. Some types of builds (like RAPIDS devcontainers) prefer to use the system-installed nvCOMP to one provided by wheels.
This ensures that preference is respected, because those builds pass matrix selector `use_cuda_wheels=false` through `rapids-dependency-file-generator` (https://github.com/rapidsai/devcontainers/pull/382).
Similar changes in cuDF: https://github.com/rapidsai/cudf/pull/17774
> allow deselecting nvcomp wheels

- cpp/include/kvikio/defaults.hpp
- cpp/include/kvikio/file_handle.hpp
- cpp/include/kvikio/shim/cufile.hpp
- cpp/include/kvikio/shim/utils.hpp
- cpp/src/defaults.cpp
- cpp/src/file_handle.cpp
- cpp/src/shim/cufile.cpp
- cpp/src/shim/utils.cpp
This PR performs makes the following three improvements:
- Separates interface and definition for `file_handle.hpp` that was missed in the previous PR https://github.com/rapidsai/kvikio/pull/581.
- To help avoid UB (e.g. program crash) for downstream applications, adds the following qualifying remark to the returned future object of `pread/pwrite`:
>The `std::future` object's `wait()` or `get()` should not be called after the lifetime of the FileHandle object ends. Otherwise, the behavior is undefined.
- Add `noexcept` specifier to compatibility mode-related functions.
> Separate more interface and definition. Add comments on std::future. Mark noexcept to compat mode-related functions

- cpp/include/kvikio/batch.hpp
- cpp/include/kvikio/buffer.hpp
- cpp/include/kvikio/cufile/config.hpp
- cpp/include/kvikio/defaults.hpp
- cpp/include/kvikio/error.hpp
- cpp/include/kvikio/file_handle.hpp
- cpp/include/kvikio/posix_io.hpp
- cpp/include/kvikio/shim/cufile_h_wrapper.hpp
- cpp/include/kvikio/shim/libcurl.hpp
- cpp/include/kvikio/shim/utils.hpp
- cpp/include/kvikio/stream.hpp
- cpp/include/kvikio/utils.hpp
- cpp/src/batch.cpp
- cpp/src/buffer.cpp
- cpp/src/cufile/config.cpp
- cpp/src/cufile/driver.cpp
- cpp/src/defaults.cpp
- cpp/src/file_handle.cpp
- cpp/src/posix_io.cpp
- cpp/src/shim/cuda.cpp
- cpp/src/shim/utils.cpp
- cpp/src/stream.cpp
- cpp/src/utils.cpp
- cpp/tests/test_basic_io.cpp
- cpp/tests/test_defaults.cpp
- cpp/tests/utils.hpp
- java/src/main/native/src/CuFileJni.cpp
This small PR applies east const style using `clang-format`. This makes KvikIO consistent with cuDF in coding style. The following parameters were applied to `.clang-format` for auto-reformatting. The file `.clang-format` itself is not updated in this PR.
```
QualifierAlignment: Custom
QualifierOrder: [inline, static, type, const, volatile]
```
In addition, this PR fixes minor "missing header" issues reported by `clang-tidy`.
> Apply east const using clang-format. Fix header issues reported by clang-tidy

- cpp/CMakeLists.txt
- cpp/include/kvikio/error.hpp
- cpp/include/kvikio/file_handle.hpp
- cpp/include/kvikio/file_utils.hpp
- cpp/src/error.cpp
- cpp/src/file_handle.cpp
- cpp/src/file_utils.cpp
> Add RAII file wrappers to avoid resource leak

- ci/build_wheel.sh
- ci/build_wheel_cpp.sh
- ci/test_wheel.sh
Uses a retry wrapper for `pip` commands to try to alleviate CI failures due to hash mismatches that result from network hiccups
xref rapidsai/build-planning#148
This will retry failures that show up in CI like:
```
Collecting nvidia-cublas-cu12 (from libraft-cu12==25.2.*,>=0.0.0a0)
Downloading https://pypi.nvidia.com/nvidia-cublas-cu12/nvidia_cublas_cu12-12.8.3.14-py3-none-manylinux_2_27_aarch64.whl (604.9 MB)
━━━━━━━━━━━━━━━━━━━━━                 350.2/604.9 MB 229.2 MB/s eta 0:00:02
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
nvidia-cublas-cu12 from …
```
> Use `rapids-pip-retry` in CI jobs that might need retries

- ci/build_cpp.sh
- ci/build_python.sh
The nightly package versions are currently not being correctly assigned.
> Fix package versioning

- .pre-commit-config.yaml
- ci/build_docs.sh
- ci/build_wheel_cpp.sh
- ci/build_wheel_python.sh
- ci/check_style.sh
- ci/release/update-version.sh
- ci/test_cpp.sh
- ci/test_python.sh
- ci/test_wheel.sh
- ci/validate_wheel.sh
`shellcheck` is a fast, static analysis tool for shell scripts. It's good at
flagging up unused variables, unintentional glob expansions, and other potential
execution and security headaches that arise from the wonders of `bash` (and
other shlangs).
This PR adds a `pre-commit` hook to run `shellcheck` on all of the `sh-lang`
files in the `ci/` directory, and the changes requested by `shellcheck` to make
the existing files pass the check.
xref: rapidsai/build-planning#135
> Add `shellcheck` to pre-commit and fix warnings

- conda/recipes/kvikio/meta.yaml
- conda/recipes/libkvikio/meta.yaml
This uses the `RAPIDS_PACKAGE_VERSION` values set in #616. This ensures we have consistent nightly versions.
This PR is independent of #622 (it is needed regardless of whether that PR is closed or merged).
> Use rapids-generate-version for package versions

- ci/build_wheel.sh
- ci/build_wheel_cpp.sh
- ci/test_wheel.sh
- cpp/CMakeLists.txt
- cpp/cmake/thirdparty/get_libcurl.cmake
- cpp/include/kvikio/shim/utils.hpp
- cpp/src/shim/utils.cpp
- python/kvikio/kvikio/_lib/CMakeLists.txt
Manual forward merge from 25.02 to 25.04. This PR should not be squashed.
> Forward-merge branch-25.02 into branch-25.04

- cpp/CMakeLists.txt
- cpp/doxygen/main_page.md
- cpp/include/kvikio/compat_mode.hpp
- cpp/include/kvikio/defaults.hpp
- cpp/include/kvikio/error.hpp
- cpp/include/kvikio/file_handle.hpp
- cpp/src/batch.cpp
- cpp/src/compat_mode.cpp
- cpp/src/defaults.cpp
- cpp/src/file_handle.cpp
- docs/source/runtime_settings.rst
This PR improves the readability of compatibility mode handling.
The current way of determining FileHandle's compatibility mode is somewhat complicated and unintuitive. The data member `_compat_mode` accompanied by some utility functions more or less combines 3 different things into one:
- The initially requested compat mode (`ON`/`OFF`/`AUTO`)
- The capability of performing synchronous cuFile I/O (bool)
- The capability of performing asynchronous cufile I/O (bool)
The disadvantages include:
- `FileHandle::is_compat_mode_preferred()` always derives the preferred compat mode on the fly as opposed to getting an already determined value.
- `FileHandle::is_compat_mode_preferred_for_async(CompatMode)` is potentially throwing, which is asymmetric to `is_compat_mode_preferred()`. Also when the …
> Adjust the way of determining FileHandle's compatibility mode for sync and async I/O to improve code readability

- cpp/CMakeLists.txt
- cpp/include/kvikio/nvtx.hpp
- cpp/include/kvikio/parallel_operation.hpp
- cpp/include/kvikio/posix_io.hpp
- cpp/include/kvikio/utils.hpp
- cpp/src/file_handle.cpp
- cpp/src/nvtx.cpp
- cpp/src/posix_io.cpp
- cpp/src/remote_handle.cpp
- cpp/src/utils.cpp
- cpp/tests/test_basic_io.cpp
This PR implements the basic feature outlined in #631. 
The two good-to-haves are currently blocked.
> Enable tracing of thread pool tasks using NVTX

- cpp/examples/basic_io.cpp
- cpp/include/kvikio/defaults.hpp
- cpp/src/defaults.cpp
- docs/source/api.rst
- docs/source/runtime_settings.rst
- python/kvikio/kvikio/_lib/defaults.pyx
- python/kvikio/kvikio/benchmarks/http_io.py
- python/kvikio/kvikio/benchmarks/s3_io.py
- python/kvikio/kvikio/benchmarks/single_node_io.py
- python/kvikio/kvikio/benchmarks/utils.py
- python/kvikio/kvikio/benchmarks/zarr_io.py
- python/kvikio/kvikio/cufile_driver.py
- python/kvikio/kvikio/defaults.py
- python/kvikio/kvikio/utils.py
- python/kvikio/tests/conftest.py
- python/kvikio/tests/test_basic_io.py
- python/kvikio/tests/test_cufile_driver.py
- python/kvikio/tests/test_defaults.py
- python/kvikio/tests/test_http_io.py
- python/kvikio/tests/test_s3_io.py
Closes https://github.com/rapidsai/kvikio/issues/642
Closes #526 
This PR makes the following changes:
This PR lets the properties in `kvikio.defaults` and `kvikio.cufile_driver` be set using a friendly Pythonic interface (C++ interface has also been adjusted for improved clarity). The expression below can appear standalone which sets the properties globally, or in a `with` statement which sets the properties via a context manager.
- To set one or more properties
```python
kvikio.defaults.set({"prop1": value1, "prop2": value2})
kvikio.cufile_driver.set({"prop1": value1, "prop2": value2})
with kvikio.defaults.set({"prop1": value1, "prop2": value2}):
with kvikio.cufile_driver.set({"prop1": value1, "prop2": value2}):
...
```
- To set a single property
```python
kvikio.defaults.set("prop", …
```
> Improve config handling in cpp and python

- cpp/include/kvikio/defaults.hpp
- cpp/include/kvikio/error.hpp
- cpp/include/kvikio/parallel_operation.hpp
- cpp/include/kvikio/posix_io.hpp
- cpp/include/kvikio/shim/cuda_h_wrapper.hpp
- cpp/include/kvikio/shim/libcurl.hpp
- cpp/include/kvikio/utils.hpp
- cpp/src/batch.cpp
- cpp/src/compat_mode.cpp
- cpp/src/cufile/driver.cpp
- cpp/src/defaults.cpp
- cpp/src/error.cpp
- cpp/src/file_handle.cpp
- cpp/src/file_utils.cpp
- cpp/src/http_status_codes.cpp
- cpp/src/remote_handle.cpp
- cpp/src/shim/cuda.cpp
- cpp/src/shim/cufile.cpp
- cpp/src/shim/libcurl.cpp
- cpp/src/shim/utils.cpp
- cpp/src/stream.cpp
- cpp/src/utils.cpp
- python/kvikio/tests/test_cufile_driver.py
- python/kvikio/tests/test_defaults.py
This PR follows cuDF's [enhanced exception handling approach](https://github.com/rapidsai/cudf/blob/branch-25.04/cpp/include/cudf/utilities/error.hpp#L178) and adds the macros `KVIKIO_EXPECT` and `KVIKIO_FAIL` to KvikIO. 
The benefit is that the file name and line number where the exception is thrown are automatically included in the exception message. This also leads to cleaner code.
This PR does not add the stacktrace capability as in cuDF's exception handling. This feature should be added in the future.
Closes #654
> Add macros KVIKIO_EXPECT and KVIKIO_FAIL to improve exception handling

- cpp/CMakeLists.txt
- cpp/benchmarks/CMakeLists.txt
- cpp/benchmarks/threadpool/threadpool_benchmark.cpp
- cpp/examples/CMakeLists.txt
- python/libkvikio/CMakeLists.txt
Partially addresses https://github.com/rapidsai/kvikio/issues/606
This PR kick-starts the process of adding benchmarks to KvikIO. The following tasks are done:
- Add CMake scripts for the benchmark.
- Add a simple benchmark for the threadpool.
To build and run the benchmark programs in the dev container:
```
build-kvikio-cpp -DBUILD_TESTS=ON -DBUILD_BENCHMARKS=ON -j 16
~/kvikio/cpp/build/latest/benchmarks/<benchmark-name>
```
Sample output:
```
2025-03-14T04:38:46+00:00
Running ./THREADPOOL_BENCHMARK
Run on (16 X 5050 MHz CPU s)
CPU Caches:
L1 Data 32 KiB (x8)
L1 Instruction 32 KiB (x8)
L2 Unified 1024 KiB (x8)
L3 Unified 98304 KiB (x1)
Load Average: 0.34, 1.07, 1.22
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead. …
```
> Add C++ benchmarks (part 1/n)

- cpp/src/shim/libcurl.cpp
It is not possible to compile the project under openSUSE Tumbleweed 20250224 (libstdc++6-devel-gcc14 14.2.1+git10750).
Without explicit `#include <algorithm>` I was getting the following error when running `/build.sh libcudf` in cudf project:
```
[ 34%] Built target libcurl_static
[ 34%] Building CXX object _deps/kvikio-build/CMakeFiles/kvikio.dir/src/shim/libcurl.cpp.o
/home/tomas/Development/playground/cudf/cpp/build/_deps/kvikio-src/cpp/src/shim/libcurl.cpp: In member function ‘void kvikio::CurlHandle::perform()’:
/home/tomas/Development/playground/cudf/cpp/build/_deps/kvikio-src/cpp/src/shim/libcurl.cpp:143:17: error: no matching function for call to ‘find(std::vector<int>::const_iterator, std::vector<int>::const_iterator, long int&)’
143 |       (std::find(http_status_codes.begin(), …
```
> Fix compilation error under openSUSE Tumbleweed

- cpp/include/kvikio/nvtx.hpp
- cpp/include/kvikio/posix_io.hpp
- cpp/include/kvikio/threadpool_wrapper.hpp
- cpp/src/bounce_buffer.cpp
- cpp/src/buffer.cpp
- cpp/src/compat_mode.cpp
- cpp/src/defaults.cpp
- cpp/src/file_handle.cpp
- cpp/src/file_utils.cpp
- cpp/src/posix_io.cpp
- cpp/src/remote_handle.cpp
- cpp/src/stream.cpp
Previously, to add NVTX function annotation for profiling, one of the following methods is used:
```cpp
namespace kvikio::detail {
// Method 1
void f() {
KVIKIO_NVTX_FUNC_RANGE();
}
// Method 2
void f() {
KVIKIO_NVTX_SCOPED_RANGE("detail::f()", 0);
}
} // end namespace kvikio::detail
```
Method 1 has the limitation that:
- `__func__` is used as the function name, which is unqualified and contains no information on namespace. Function overloads cannot be well handled.
- Users cannot specify NVTX payload or color.
- There is no way to annotate a lambda. Any lambda is simply named `operator()`.
Method 2 has the limitation that:
- Users have to manually enter the function name. Naming inconsistency has been observed across different source files.
- Users have to specify an NVTX payload value. …
> Improve NVTX annotation for functions

- cpp/include/kvikio/parallel_operation.hpp
- cpp/include/kvikio/utils.hpp
- cpp/src/utils.cpp
So far the parameter page size in KvikIO has been a compile-time constant (4K). On GH200, however, the page size is 64K. This PR makes it portable by querying its value at runtime.
> Make page size portable by querying it at runtime

- python/kvikio/kvikio/zarr/_zarr_python_3.py
This adds compatibility for zarr-python 3.0.7, which changed the dtype for representing bytes in https://github.com/zarr-developers/zarr-python/pull/2738.
> zarr-python 3.0.7 compatibility

- cpp/include/kvikio/file_utils.hpp
- cpp/src/file_utils.cpp
- cpp/src/utils.cpp
- python/kvikio/kvikio/__init__.py
- python/kvikio/kvikio/_lib/file_handle.pyx
- python/kvikio/kvikio/cufile.py
- python/kvikio/tests/test_basic_io.py
This PR provides a utility function `get_page_cache_info(file)` in C++ and Python to check how many pages of a file are resident in the page cache of the Linux kernel.
This PR is a byproduct of a recent investigation of an issue on GH200 system, where the sudo command that drops the page cache doesn't seem to achieve the expected effect.
This feature is functionally similar to the Linux utility program `fincore`, which is also based on the system call `mincore` used in this PR.
> Add the feature to check page cache residency information for a file

- python/kvikio/kvikio/benchmarks/utils.py
In UCX-Py and UCXX, we skip querying memory info on MIG devices as the approach we use on other hardware doesn't work for MIG. However KvikIO did not skip querying memory info on MIG, which causes this code to fail there.
To fix this issue, we adapt the approach used in UCX-Py and UCXX to KvikIO, which allows this code to run on MIG.
Additionally the code used one `try...except...` to handle everything from `import`ing to querying the device. With the MIG check too, this becomes kind of unwieldy for one `try...except...`. So this moves the `import` to the top-level and breaks up the `try...except...`. This makes the logic of the code and the cases it handles a bit more legible to readers 
Fixes https://github.com/rapidsai/kvikio/issues/701
> Fix benchmark code on MIG

- .github/workflows/build.yaml
- .github/workflows/pr.yaml
- .github/workflows/test.yaml
- .github/workflows/trigger-breaking-change-alert.yaml
- conda/environments/all_cuda-118_arch-aarch64.yaml
- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-128_arch-aarch64.yaml
- conda/environments/all_cuda-128_arch-x86_64.yaml
- cpp/doxygen/main_page.md
- dependencies.yaml
- docs/source/install.rst
- python/kvikio/pyproject.toml
- python/libkvikio/pyproject.toml
Contributes to https://github.com/rapidsai/build-planning/issues/120
This PR adds support for Python 3.13.
This is part of ongoing work to add Python 3.13 support across RAPIDS.
It temporarily introduces a build/test matrix including Python 3.13, from https://github.com/rapidsai/shared-workflows/pull/268.
A follow-up PR will revert back to pointing at the `branch-25.06` branch of `shared-workflows` once all
RAPIDS repos have added Python 3.13 support.
CI here is expected to fail until all of this project's upstream dependencies support Python 3.13.
This can be merged whenever all CI jobs are passing.
> feat: add support for Python 3.13

- conda/recipes/kvikio/recipe.yaml
- conda/recipes/libkvikio/recipe.yaml
This quotes `head_rev` to ensure that commits with leading zeros in the git SHA include those zeros in the output package name.
xref: https://github.com/rapidsai/build-planning/issues/176
> Quote head_rev in conda recipes

- .pre-commit-config.yaml
- cpp/src/file_utils.cpp
- cpp/src/shim/utils.cpp
Contributes to https://github.com/rapidsai/build-planning/issues/177
This PR updates the clang version to 20.
> Update to clang 20

- .devcontainer/cuda12.8-conda/devcontainer.json
- .devcontainer/cuda12.8-pip/devcontainer.json
- .github/workflows/build.yaml
- .github/workflows/pr.yaml
- .github/workflows/test.yaml
- .github/workflows/trigger-breaking-change-alert.yaml
- conda/environments/all_cuda-128_arch-aarch64.yaml
- conda/environments/all_cuda-128_arch-x86_64.yaml
- cpp/doxygen/main_page.md
- dependencies.yaml
- docs/source/install.rst
This PR reverts shared-workflows branches to `branch-25.06` and ensures builds use CUDA 12.8.
CUDA 12.9 will be used in the test matrix but not for builds in RAPIDS 25.06. See https://github.com/rapidsai/build-planning/issues/173#issuecomment-2882179838 for more information.
> Finish CUDA 12.9 migration and use branch-25.06 workflows

- python/kvikio/kvikio/utils.py
This PR fixes a doc build error by removing unnecessary indentations from the docstring.
The current doc build error in the CI:
> /opt/conda/envs/docs/lib/python3.13/site-packages/kvikio/utils.py:docstring of kvikio.utils.kvikio_deprecation_notice.<locals>.decorator.<locals>.wrapper:5: WARNING: Explicit markup ends without a blank line; unexpected unindent. [docutils]
is caused by the extra indentation, for instance, to the left of `Reset the default task size ...`
```
.. deprecated:: 25.04 Use :meth:`kvikio.defaults.set()` instead.
Reset the default task size used for parallel IO operations.
Parameters
----------
nbytes : int
The default task size in bytes.
```
> Fix doc build error

- .github/workflows/build.yaml
- .github/workflows/pr.yaml
- .github/workflows/test.yaml
- ci/build_wheel.sh
- ci/build_wheel_cpp.sh
- ci/build_wheel_python.sh
- ci/test_wheel.sh
Proposes a batch of small, mostly-unrelated changes to building and packaging.
These are all part of RAPIDS-wide efforts to make it easier to reproduce CI locally and to use artifacts from one project's CI in another project's CI.
Contributes to https://github.com/rapidsai/build-planning/issues/178
* prevents triggering expensive CI jobs based on PRs modifying `ci/release/update-version.sh`
Contributes to https://github.com/rapidsai/shared-workflows/issues/356
* explicitly provides an input for `script` to workflows using it, instead of relying on a default value coming from the workflow file
Contributes to https://github.com/rapidsai/shared-workflows/issues/337
* switches from input `run_script` to `script` in uses of the `custom-job` workflow
Contributes to …
> use 'rapids-init-pip' in wheel CI, other CI changes

- python/kvikio/kvikio/_lib/arr.pyx
Follow up on this discussion: https://github.com/rapidsai/kvikio/pull/692#discussion_r2038772497
Ensure that the acquired buffer is properly released even if an exception is raised. Given we may raise an exception, this is important to check.
cc @vyasr
> Use `try...finally...` to ensure buffer is released

- ci/build_cpp.sh
- ci/build_python.sh
- ci/build_wheel_cpp.sh
- ci/build_wheel_python.sh
Contributes to https://github.com/rapidsai/build-planning/issues/181
* removes all uploads of conda packages and wheels to `downloads.rapids.ai`
Looked for uses of the relevant `gha-tools` tools, as well as documentation about `downloads.rapids.ai`, being on the NVIDIA VPN, using S3, etc. like this:
```shell
git grep -i -E 's3|upload|downloads\.rapids|vpn'
```
See "How I tested this" on https://github.com/rapidsai/shared-workflows/pull/364
> stop uploading packages to downloads.rapids.ai

- cpp/include/kvikio/defaults.hpp
- cpp/src/defaults.cpp
- cpp/tests/CMakeLists.txt
- cpp/tests/test_defaults.cpp
- cpp/tests/utils/env.cpp
- cpp/tests/utils/env.hpp
This PR performs the following items:
- Add a new overload `kvikio::getenv_or` that supports env var alias, i.e. multiple different env vars referring to the same property.
- Add new env var `KVIKIO_NUM_THREADS` as the alias of `KVIKIO_NTHREADS`, and add new C++ API `num_threads`/`set_thread_pool_nthreads` as the alias of existing `thread_pool_nthreads`/`set_thread_pool_nthreads`. This makes C++ and Python API (i.e. `kvikio.defaults.get("num_threads")`) consistent.
- Fix a well-hidden UB related to string temporaries and `std::initializer_list`.
> Add an overload getenv_or that supports env var alias. Add new env var KVIKIO_NUM_THREADS. Fix UB.

- ci/build_cpp.sh
- conda/recipes/libkvikio/recipe.yaml
This is a temporary patch for the problem that cufile is not available on arm before CUDA 12.2, which results in these libkvikio packages not currently being installable on (for example) CUDA 12.0 arm systems. We should follow this PR up with a fix to actually build separate packages for older and newer CUDA versions, but this quick fix should unblock other work today.
> Only use cufile on x86

- cpp/tests/test_defaults.cpp
- cpp/tests/test_remote_handle.cpp
KvikIO unit test has a utility class `EnvVarContext` class, introduced in https://github.com/rapidsai/kvikio/pull/700, and slightly improved in https://github.com/rapidsai/kvikio/pull/735. It has been identified that this class was incorrectly initialized, resulting in UB: it causes the unit test failure in C++20, which by fluke was not observed in C++17. This PR fixes this error. Specifically, the constructor of `EnvVarContext` is:
```
EnvVarContext(std::initializer_list<std::pair<std::string_view, std::string_view>> env_var_entries);
```
There are several ways of instantiation:
```
// Direct initialization
EnvVarContext env_var_ctx({{"env_1", "v1"}, {"env_2", "v2"}});
// Direct list initialization
EnvVarContext env_var_ctx{{"env_1", "v1"}, {"env_2", "v2"}};
// Copy list initialization …
```
> Fix unit test UB resulting from incorrect initialization

- ci/build_cpp.sh
- conda/recipes/libkvikio/recipe.yaml
Simplify the logic necessary to handle compiler versions by folding it into the context.
> Set compiler versions in context

- ci/build_cpp.sh
We need to drop the CUDA patch version from `cuda_version`.
> Use RAPIDS' CUDA major-minor version in Conda's `cuda_version`

- .devcontainer/cuda12.9-conda/devcontainer.json
- .devcontainer/cuda12.9-pip/devcontainer.json
- .github/workflows/pr.yaml
- conda/environments/all_cuda-129_arch-aarch64.yaml
- conda/environments/all_cuda-129_arch-x86_64.yaml
- cpp/doxygen/main_page.md
- dependencies.yaml
- docs/source/install.rst
Addressing issues:
* https://github.com/rapidsai/build-planning/issues/195
* https://github.com/rapidsai/build-planning/issues/173
Use CUDA 12.9 throughout different build and test environments.
> Use CUDA 12.9 in Conda, Devcontainers, Spark, GHA, etc.

- python/kvikio/kvikio/remote_file.py
- python/kvikio/tests/test_s3_io.py
AWS S3 object key name is case sensitive. Current implementation of `open_s3_url` converts all the letters of URL to lowercase before passing it to the wrapped C++ library. As a result, if the object key name contains any capital letter, the following error will occur:
```
RuntimeError: KvikIO failure at: /home/coder/kvikio/cpp/src/shim/libcurl.cpp:176: curl_easy_perform() error (The requested URL returned error: 404)
```
This PR fixes this issue by forwarding the user-provided URL as-is.
> Fix a case sensitivity bug in S3 remote I/O

- conda/environments/all_cuda-129_arch-aarch64.yaml
- conda/environments/all_cuda-129_arch-x86_64.yaml
- conda/recipes/kvikio/recipe.yaml
- dependencies.yaml
The `nvcomp` conda package is being split into a C++ package `libnvcomp` and a Python bindings package `nvcomp`. We want to use the C++ package only, so we are adopting `libnvcomp`.
> Use libnvcomp conda package

- cpp/include/kvikio/remote_handle.hpp
- cpp/src/remote_handle.cpp
- python/kvikio/kvikio/_lib/remote_handle.pyx
- python/kvikio/kvikio/remote_file.py
Knowing the size of the remote file before reading is important in remote I/O, as it allows users to pre-allocate buffer to avoid expensive on-the-fly reallocation. Currently in KvikIO this is not possible for AWS S3 presigned URL, which is a special link generated by data owner to grant time-limited access without using AWS credentials.
As is described in #585, file size query in KvikIO results in the HTTP 403 (forbidden) status code. This is because the query method is based on the `HEAD` request, and AWS S3 does not allow `HEAD` for presigned URL.
This PR provides a solution. The idea is to send a `GET` request (instead of `HEAD`) with a 1-byte range, so that we can still obtain the header information at a negligible cost. Since the `content-length` header is now at a fixed value of 1, …
> Support file size query for S3 presigned URL

- conda/recipes/libkvikio/recipe.yaml
Fixes an issue where CUDA 13 packages named like `linux-aarch64/libkvikio-25.10.00a43-cuda13_0_250916_b69d9aea.conda` were getting dependencies on `cuda-version >=12.2.0a0,<14.0a0`, which allowed them to be used in CUDA 12 environments. That is not desired and could cause problems.
> Fix CUDA 13 handling of libcufile on aarch64

- cpp/src/nvtx.cpp
> Keep string alive until nvtxDomainResourceCreate

- cpp/src/remote_handle.cpp
`kvikio::RemoteHandle::open()` has started to support public S3 since https://github.com/rapidsai/kvikio/pull/820. When `open()` sees an S3 URL, it first assumes a private S3 object and queries its size. If the query fails, it proceeds to assume that the file is a public S3.
During the construction of a private S3 object, the constructor scans the environment variables for AWS credentials. Manual testing of https://github.com/rapidsai/kvikio/pull/820 accidentally includes the env vars all the time and hides a bug: in absence of env vars, the constructor of the private S3 object will throw an exception, which is unhandled, and KvikIO never gets a chance to try with public S3.
This PR fixes this bug.
> Fix a bug in public S3 inference

- cpp/src/compat_mode_manager.cpp
The current condition has a redundant clause. If the requested compat mode is `CompatMode::OFF`, then `_is_compat_mode_preferred` is always false. All of the fallback conditions that are checked in the constructor that could result in `_is_compat_mode_preferred` being true only hold when the user requests `CompatMode::AUTO`.
> Simplify async validation condition
