rapidsai/kvikio

- python/benchmarks/single-node-io.py
- python/tests/test_benchmarks.py
- scripts/format-all.py
Adding test of the `single-node-io.py` benchmark
> Test benchmarks

- cpp/CMakeLists.txt
- cpp/examples/CMakeLists.txt
- cpp/examples/basic_io.cpp
- cpp/include/kvikio/buffer.hpp
- cpp/include/kvikio/config.hpp
- cpp/include/kvikio/driver.hpp
- cpp/include/kvikio/file_handle.hpp
- cpp/include/kvikio/shim.hpp
- cpp/include/kvikio/shim/cufile.hpp
- cpp/include/kvikio/utils.hpp
- python/benchmarks/single-node-io.py
- python/setup.py
Use dlopen and dlsym to load the cuFile API
Removing the `STATIC_CUFILE` build option
> Shim layer

- cpp/include/kvikio/config.hpp
- cpp/include/kvikio/utils.hpp
Fixes https://github.com/rapidsai/kvikio/issues/11
@gigony can you confirm that this PR fixes the WSL issue?
> Enable compat mode when runnning in WSL

- cpp/include/kvikio/posix_io.hpp
Reuse the buffers used for POSIX read and write
> POSIX read/write reuse allocations

- ci/cpu/build.sh
- conda/recipes/kvikio/meta.yaml
- conda/recipes/libkvikio/build.sh
- conda/recipes/libkvikio/meta.yaml
Still WIP. Includes a couple changes to the recipes and CI scripts.
> Build improvements

- ci/cpu/upload.sh
Follow up to PR ( https://github.com/rapidsai/kvikio/pull/27 )
Now that `libkvikio` builds seem to be working, upload the packages as well.
> Upload `libkvikio`

- cpp/include/kvikio/config.hpp
> Clean up config

- .github/ops-bot.yaml
This file controls which features of the `ops-bot` tool are enabled on this repository.
> Add `ops-bot.yaml` config file

- ci/release/update-version.sh
Adds `python/CMakeLists.txt` and `scripts/format-all.py` to the version updating script, so that the RAPIDS versions in these files are automatically bumped around release time.
> Add new files to update version script

- ci/cpu/build.sh
- ci/gpu/build.sh
`kvikio` is not using Project Flash, so this PR disable it totally
> Build kvikio using libkvikio from CPU job in GPU job

- cpp/include/kvikio/defaults.hpp
- cpp/include/kvikio/file_handle.hpp
- cpp/include/kvikio/posix_io.hpp
... instead of  anon namespaces
> Use namespace kvikio::detail

- python/kvikio/cufile.py
Forward-merge triggered by push to `branch-22.08` that creates a PR to keep `branch-22.10` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-22.08 to branch-22.10 [skip gpuci]

- README.md
> Add stable channel install instruction

- README.md
xref: https://github.com/rapidsai/kvikio/issues/94#issuecomment-1212164865
> document channel_priority for conda

- docs/source/api.rst
- python/benchmarks/single-node-io.py
- python/kvikio/defaults.py
- python/kvikio/thread_pool.py
- python/tests/test_defaults.py
Closes https://github.com/rapidsai/kvikio/issues/92
> Rename `reset_num_threads()` and `reset_task_size()`

- conda/environments/kvikio_dev_cuda11.5.yml
This PR allows cupy 11.
xref: https://github.com/rapidsai/integration/pull/528
> Allow cupy 11

- CODE_OF_CONDUCT.md
This repo's `CODE_OF_CONDUCT.md` is superseded by an organization-wide policy: https://github.com/rapidsai/.github/pull/3
> Use rapidsai CODE_OF_CONDUCT.md

- CODE_OF_CONDUCT.md
Forward-merge triggered by push to `branch-22.12` that creates a PR to keep `branch-23.02` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> [gpuCI] Forward-merge branch-22.12 to branch-23.02 [skip gpuci]

- conda/environments/kvikio_dev_cuda11.5.yml
- conda/recipes/kvikio/meta.yaml
- conda/recipes/libkvikio/meta.yaml
- cpp/CMakeLists.txt
- cpp/examples/downstream/CMakeLists.txt
- python/CMakeLists.txt
- python/pyproject.toml
Also bring kvikio minimum required version inline with the rest of RAPIDS
> Don't use CMake 3.25.0 as it has a FindCUDAToolkit show stopping bug

- CHANGELOG.md
- CODE_OF_CONDUCT.md
- README.md
- conda/environments/kvikio_dev_cuda11.5.yml
- conda/recipes/kvikio/meta.yaml
- conda/recipes/libkvikio/meta.yaml
- cpp/CMakeLists.txt
- cpp/cmake/fetch_rapids.cmake
- cpp/doxygen/Doxyfile
- cpp/examples/downstream/CMakeLists.txt
- cpp/include/kvikio/shim/cufile.hpp
- cpp/include/kvikio/shim/utils.hpp
- cpp/include/kvikio/utils.hpp
- docs/source/conf.py
- python/CMakeLists.txt
- python/kvikio/numpy.py
- python/pyproject.toml
- python/setup.cfg
- python/tests/test_benchmarks.py
- python/tests/test_examples.py
- python/tests/test_numpy.py
- python/tests/test_nvcomp.py
- scripts/format-all.py
Only critical/hotfix level issues should be merged into `branch-22.12` until release (merging of this PR).
- Update documentation
- Allow testing for the new release
- Enable a means to merge `branch-22.12` into `main` for the release
> [RELEASE] kvikio v22.12

- CHANGELOG.md
Updating the changelog for past releases. cc: @raydouglass @ajschmidt8
> Update changelog for releases 22.06-22.12.

- python/tests/test_nvcomp.py
Forward-merge triggered by push to `branch-23.02` that creates a PR to keep `branch-23.04` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-23.02 to branch-23.04

- ci/release/update-version.sh
Removes a file that no longer exists
Skipping CI since this file is not tested in CI
> Fix update-version.sh [skip ci]

- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/recipes/kvikio/conda_build_config.yaml
- conda/recipes/libkvikio/conda_build_config.yaml
- dependencies.yaml
This PR updates builds to use GCC 11.
> Update to GCC 11

- .gitignore
- build.sh
- legate/CMakeLists.txt
- legate/cpp/CMakeLists.txt
Forward-merge triggered by push to `branch-23.04` that creates a PR to keep `branch-23.06` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-23.04 to branch-23.06

- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/recipes/kvikio/meta.yaml
- dependencies.yaml
> Update cupy dependency

- legate/cpp/legate_kvikio.cpp
- legate/cpp/legate_mapping.cpp
- legate/cpp/legate_mapping.hpp
- legate/cpp/tile_io.cpp
- legate/legate_kvikio/library_description.py
See https://github.com/nv-legate/legate.core/pull/675 and https://github.com/nv-legate/legate.core/pull/676
> Use the new registry and mapper API of Legate

- python/kvikio/numpy.py
fixes https://github.com/rapidsai/kvikio/issues/216
cc. @wyli
> fixed import of `ArrayLike` and `DTypeLike`

- .github/workflows/build.yaml
- README.md
- ci/build_docs.sh
- ci/docs/build.sh
- ci/release/update-version.sh
- docs/source/index.rst
Forward-merge triggered by push to `branch-23.06` that creates a PR to keep `branch-23.08` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-23.06 to branch-23.08

- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/recipes/kvikio/conda_build_config.yaml
- conda/recipes/kvikio/meta.yaml
- conda/recipes/libkvikio/conda_build_config.yaml
- cpp/CMakeLists.txt
- cpp/examples/downstream/CMakeLists.txt
- dependencies.yaml
- legate/CMakeLists.txt
- legate/pyproject.toml
- python/CMakeLists.txt
- python/pyproject.toml
Updates minimum required CMake version to 3.26.4
> Update to CMake 3.26.4

- .gitignore
- README.md
- notebooks/zarr.ipynb
Fixes #143
cc. @ivirshup @jakirkham
> Zarr notebook

- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-120_arch-x86_64.yaml
- conda/recipes/kvikio/meta.yaml
- dependencies.yaml
- legate/pyproject.toml
- python/kvikio/_lib/libkvikio.pyx
- python/kvikio/_lib/libnvcomp_ll.pyx
- python/kvikio/_lib/nvcomp_cxx_api.pxd
- python/pyproject.toml
This PR bumps the pinning and fixes the new warnings that appeared
> Update to Cython 3.0.0

- python/benchmarks/zarr-io.py
Forward-merge triggered by push to `branch-23.10` that creates a PR to keep `branch-23.12` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-23.10 to branch-23.12

- .github/workflows/build.yaml
- .github/workflows/pr.yaml
- .github/workflows/test.yaml
- dependencies.yaml
This PR builds conda packages using CUDA 12 on ARM.
Closes #281.
> kvikio: Build CUDA 12.0 ARM conda packages.

- notebooks/nvcomp_vs_zarr_lz4.ipynb
> updated the nvcomp notebook to use the new API

- cpp/cmake/fetch_rapids.cmake
Accidentally didn't commit this change in #314.
> Revert rapids-cmake branch.

- .github/workflows/pr.yaml
- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-120_arch-x86_64.yaml
- conda/recipes/kvikio/conda_build_config.yaml
- cpp/CMakeLists.txt
- cpp/cmake/thirdparty/get_gtest.cmake
- dependencies.yaml
- python/kvikio/_lib/libnvcomp.pyx
- python/kvikio/_lib/nvcomp_cxx_api.pxd
- python/kvikio/nvcomp.py
- python/tests/test_nvcomp.py
Manual forward merge from 23.12 to 24.02. This PR should not be squashed.
Closes #317.
> Forward-merge branch-23.12 to branch-24.02

- build.sh
Forward-merge triggered by push to `branch-24.02` that creates a PR to keep `branch-24.04` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-24.02 to branch-24.04

- cpp/CMakeLists.txt
- cpp/cmake/thirdparty/get_nvtx.cmake
- cpp/include/kvikio/file_handle.hpp
- cpp/include/kvikio/posix_io.hpp
- cpp/include/kvikio/utils.hpp
- docs/source/quickstart.rst
> Adding NVTX annotations 

- .devcontainer/cuda11.8-conda/devcontainer.json
- .devcontainer/cuda11.8-pip/devcontainer.json
- .devcontainer/cuda12.5-conda/devcontainer.json
- .devcontainer/cuda12.5-pip/devcontainer.json
- ci/release/update-version.sh
- cpp/include/kvikio/file_handle.hpp
- cpp/scripts/run-cmake-format.sh
- dependencies.yaml
- python/kvikio/pyproject.toml
- python/libkvikio/pyproject.toml
Fix forward-merge conflict: https://github.com/rapidsai/kvikio/pull/420
> Manual forward-merge: branch 24.10 merge 24.08

- cpp/CMakeLists.txt
- cpp/include/kvikio/utils.hpp
> Fix no-cuda build

- python/kvikio/CMakeLists.txt
See https://github.com/rapidsai/devcontainers/pull/414
> Fix case of find_package call

- .devcontainer/cuda12.8-conda/devcontainer.json
- .devcontainer/cuda12.8-pip/devcontainer.json
- .github/workflows/build.yaml
- .github/workflows/pr.yaml
- .github/workflows/test.yaml
- .github/workflows/trigger-breaking-change-alert.yaml
- conda/environments/all_cuda-128_arch-aarch64.yaml
- conda/environments/all_cuda-128_arch-x86_64.yaml
- cpp/doxygen/main_page.md
- dependencies.yaml
- docs/source/install.rst
This PR uses CUDA 12.8.0 to build and test.
xref: https://github.com/rapidsai/build-planning/issues/139
> Build and test with CUDA 12.8.0

- .devcontainer/cuda12.8-conda/devcontainer.json
- .devcontainer/cuda12.8-pip/devcontainer.json
- .github/workflows/pr.yaml
- conda/environments/all_cuda-128_arch-aarch64.yaml
- conda/environments/all_cuda-128_arch-x86_64.yaml
- cpp/doxygen/main_page.md
- dependencies.yaml
- docs/source/install.rst
Manual forward merge from 25.02 to 25.04. This PR should not be squashed.
> Forward-merge branch-25.02 to branch-25.04

- cpp/include/kvikio/shim/utils.hpp
- cpp/src/shim/utils.cpp
> Use std::string

- cpp/CMakeLists.txt
- cpp/cmake/thirdparty/get_libcurl.cmake
- python/kvikio/kvikio/_lib/CMakeLists.txt
Also don't export the curl dependency.
> Set `POSITION_INDEPENDENT_CODE` on libcurl

- ci/test_java.sh
- dependencies.yaml
Issue: https://github.com/rapidsai/build-planning/issues/22
> Consolidate more Conda solves in CI

- docs/source/install.rst
This adds documentation on how to install KvikIO from PyPI
> add install docs

- .pre-commit-config.yaml
> Remove `FindCUDAToolkit.cmake` from `.pre-commit-config.yaml`

- cpp/examples/CMakeLists.txt
- cpp/tests/CMakeLists.txt
> Fix an RPATH-related bug for CMake install

- ci/release/update-version.sh
Update the java `pom.xml` in `update-version.sh`.
Copied from https://github.com/rapidsai/cudf/blob/branch-25.04/ci/release/update-version.sh#L90-L92
Skipping CI since this file is not tested in CI.
> Add pom.xml to update-version.sh

- ci/release/update-version.sh
Adds necessary missing variables
> Another fix to update-version

- conda/environments/all_cuda-118_arch-aarch64.yaml
- conda/environments/all_cuda-118_arch-x86_64.yaml
- conda/environments/all_cuda-128_arch-aarch64.yaml
- conda/environments/all_cuda-128_arch-x86_64.yaml
- cpp/doxygen/main_page.md
- dependencies.yaml
- docs/source/install.rst
- python/kvikio/pyproject.toml
- python/libkvikio/pyproject.toml
> resolve forward-merge from branch-25.06 to branch-25.08

- .devcontainer/cuda12.9-conda/devcontainer.json
- .devcontainer/cuda12.9-pip/devcontainer.json
- .github/workflows/build.yaml
- .github/workflows/pr.yaml
- .github/workflows/test.yaml
- .github/workflows/trigger-breaking-change-alert.yaml
- conda/environments/all_cuda-129_arch-aarch64.yaml
- conda/environments/all_cuda-129_arch-x86_64.yaml
- cpp/doxygen/main_page.md
- dependencies.yaml
- docs/source/install.rst
This PR uses CUDA 12.9.0 to build and test.
xref: https://github.com/rapidsai/build-planning/issues/173
> Build and test with CUDA 12.9.0

- .github/CODEOWNERS
- .pre-commit-config.yaml
- .shellcheckrc
- build.sh
- cpp/scripts/run-cmake-format.sh
xref rapidsai/build-planning#135
> refactor(shellcheck): enable for all files and fix remaining warnings

- cpp/doxygen/main_page.md
- docs/source/install.rst
- python/kvikio/pyproject.toml
As part of #768, remove CUDA 11 from docs.
> Remove CUDA 11 mentions from docs
